### ISSUE TITLE
Reports not building

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/traits.build#101]
Something small is not working with the reports building - in the categorical traits section.

To be explored further.

**Comment by dfalster** [comment]
I thought there was test for this function?

**Comment by ehwenk** [comment]
I talked to Sophie and there is - once I work out what is wrong, I'll figure out why the test didn't pick it up

**Comment by ehwenk** [comment]
Closed with [4a1674d](https://github.com/traitecoevo/traits.build/commit/4a1674d45dbd9f6d2b0eed1487c3367f7525f83e)
