### ISSUE TITLE
Create a hex sticker

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/traits.build#105]
We need a sticker!

I've created a branch called `hex-sticker` with code, but need a design. 

@ehwenk suggests database icon with some tools - i.e. hammer + spanner

**Comment by ehwenk** [comment]
First draft: 

![Image](https://github.com/traitecoevo/traits.build/assets/8701562/354d5148-c84f-4c50-8034-4f19b86e237d)

@yangsophieee  suggestions: make spanner transparent (currently handle is filled with white); make `traits.build` words larger; center words and database icon

I think we should add the `austraits` gum leaves at the top (tiny)
