### ISSUE TITLE
Duplicate trait values do not get collapsed

### ISSUE THREAD

**Issue by yangsophieee** [traitecoevo/traits.build#11]
Similar issue to [this one](https://github.com/traitecoevo/traits.build/issues/3):

Currently if you have trait value substitutions where multiple `find:` values have the same `replace:` field, AusTraits will not collapse those duplicate values (same `observation_id`) when building the `austraits$traits` table. When you pivot the traits table wider, as there are non-unique rows, this results in a wide table that has list data types where there should be character data types. An example of this issue is when you filter for `resprouting_capacity` in Burrows_2020 and Clarke_2015. I'm sure it is an issue for numerous other traits and studies.

**Comment by yangsophieee** [comment]
This issue doesn't make much sense to me anymore. Maybe the issue is when taxonomic updates happen and two previously distinct names got aligned to one name, leading to duplicate trait values?

**Comment by dfalster** [comment]
Need feedback from @ehwenk on this

**Comment by yangsophieee** [comment]
I found the issue -- when you get up to the step of `build_update_taxonomy`, you `left_join` the taxa table at [Line 1534](https://github.com/traitecoevo/traits.build/blob/9ca56af0e2160d8f121f8de27bae1e13eb9678b1/R/process.R#L1534) of process.R. The issue is when there are multiple rows with the `cleaned_name` in the `taxon_list.csv` table, e.g. with _Logania campanulata_, _Ozothamnus ramosus_ and _Hypoxis occidentalis var. quadriloba_, you end up with duplicate rows in the trait table. I've had a look at these taxa and I'm not exactly sure what the difference is between the two rows in the `taxon_list.csv` table. 

Would you be able to have a look @ehwenk @dfalster? Thank you!

**Comment by ehwenk** [comment]
I think there might be two issues being mixed together here. The issue with the left_join of the taxa table is a known problem - and the reason I want to have all APC & APNI names in the "starting" taxon list. There need to be unique `taxon_name` & `original_name` combinations in austraits$traits AND there need to be unique `taxon_names` in `taxon_list.csv`. I think the main source of duplication in taxon_list.csv occurs when the same new name is added on multiple branches that are combined. Of course there will continue to be new "unofficial" names add (e.g. `Acacia sp. [dataset_id]`, but we can at least avoid names from APC/APNI being added repeatedly. 

The mis-mapping of trait value substitutions is something separate that I haven't thought about. It seems odd that duplication of `replace` values is occurring for the same dataset_id. There absolutely should be a problem (that gets flagged) is the same `find` is mapped to two different `replace` values, but it will happen regularly that different `find` values are mapped to the same `replace`.

**Comment by yangsophieee** [comment]
At this point I don't think the mis-mapping of trait value substitutions is a problem, I thought that was the issue originally but it was the taxa table problem. Might have to remove this issue and make a new issue.

**Comment by yangsophieee** [comment]
I've checked both Burrows_2020 and Clarke_2015 and I believe my initial diagnosis of the problem is wrong and it is really to do with duplicates in `taxon_list.csv`. Moving to new issue: https://github.com/traitecoevo/traits.build/issues/43.
