### ISSUE TITLE
[traits.build testing] Test for checking units in metadata are correct/in the unit_conversions - units must be in units conversion file to pass the test

### ISSUE THREAD

**Issue by dcol2804** [traitecoevo/traits.build#146]
This is super minor and I've made a simple workaround but it could potentially confuse new database creators:

Not all units require a conversion and are therefore not in the unit conversions file - one example is Cel for degrees C. I have simply added the units that never need conversions to the end of the unit_from column in the unit_conversions.csv file so the test passes.

Might be worth making the list of acceptable units from those already existing in austraits too.

Here's some code I used to get them - please feel free to improve it, it should be done by purr::map but I'm a for loop diehard :)!

# load austraits
austraits = load_austraits(version = get_version_latest())

# separate out the definitions as an object (for simplicity)
def = austraits$definitions

# get a vector of all the trait names
traits = unique(austraits$traits$trait_name)

# make an empty vector
out = character()

# for each of the trait names, get the unit and add it on to the vector
for (i in 1:length(traits)){
  
  
  unit = def[[traits[i]]]$units
  
  out = unique(c(out, unit))
  
}

print(out)

**Comment by ehwenk** [comment]
Completed with https://github.com/traitecoevo/traits.build/commit/129dcf5f627a23967abb9b24657afc8c39583ef5
