### ISSUE TITLE
[traits.build workflow] Swap out remake for another build pipeline

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/traits.build#17]
arising from https://github.com/traitecoevo/austraits.build/issues/354

Austraits.build was using [remake](http://github.com/richfitz/remake), however this package isn't being maintained and will never make it to cran. 

Alternatives include drake, targets, memoise

**Comment by dfalster** [comment]
Discussed options with @cboetigg Carl suggests moving away from targets and remake, because not what average R user is used to. Instead try memoise -- R package than caches intermediates but is more light weight

Can turn memoise any function
```{r}
dataset_process2 <- memoise::memoise(dataset_process,
  cache = memoise::cache_filesystem("ignore/cache")
)
```

But won't detect changes in filenames so need to change dataset_process to accepte data rather than filename and pass in data table rather than filename

```{r}
filename_data_raw <- "data/ABRS_1981/data.csv"

data_raw  <- readr::read_csv(filename_data_raw, col_types = cols(), guess_max = 100000, progress = FALSE)
```

General setup
```{r}
library("traits.build")

schema <- get_schema()
version_number <- util_get_version("config/metadata.yml")
git_SHA <- util_get_SHA()
resource_metadata <- get_schema("config/metadata.yml", "metadata")
definitions <- get_schema("config/traits.yml", "traits")
unit_conversions <- get_unit_conversions("config/unit_conversions.csv")
taxon_list <- read_csv_char("config/taxon_list.csv")

```

Then proces study (this won't work uless also change dataset_process as suggested above)
```{r}
ABRS_1981_config <- dataset_configure("data/ABRS_1981/metadata.yml", definitions, unit_conversions)

ABRS_1981_raw <- dataset_process2(data_raw, ABRS_1981_config, schema, resource_metadata)

ABRS_1981 <- build_update_taxonomy(ABRS_1981_raw, taxon_list)
```

Can cache to disk or RAM. We probably want disk

Could add an extra step to check hash of files 

```
digest::digest(filename_data_raw, file=TRUE)
```
go full step from filesin -> fileout

Then parallellise using R's usuall workflows -- eg. furrr

**Comment by dfalster** [comment]
Hi @yangsophieee @ehwenk 

I'm working on this now. Early ideas. PLs let me know what you think.

We'll provide multiple ways to build a repo

# base R

The default will be using base R.  I think this will be easier for base R users.
```
 build_setup_pipeline(method="base", dataset_ids = c("Falster_2005_1", "Wright_2019"))
```

The following create a file `build.R` which builds the repo. E.g., from the above

```
# This file is automatically generated from traits.build 
# package, via the file remake.yml.whisker: 
# edit the file there (or the files that it includes).

# Load R resources
library(traits.build)
source("R/custom_R_code.R")

# Load data resources
schema <- get_schema()
resource_metadata <- get_schema("config/metadata.yml", "metadata")
definitions <- get_schema("config/traits.yml", "traits")
unit_conversions <- get_unit_conversions("config/unit_conversions.csv")
taxon_list <- read_csv_char("config/taxon_list.csv")

# Build each resource
Falster_2005_1_config <- dataset_configure("data/Falster_2005_1/metadata.yml", definitions, unit_conversions)
Falster_2005_1_raw <- dataset_process("data/Falster_2005_1/data.csv", Falster_2005_1_config, schema, resource_metadata)
Falster_2005_1 <- build_update_taxonomy(Falster_2005_1_raw, taxon_list)

Wright_2019_config <- dataset_configure("data/Wright_2019/metadata.yml", definitions, unit_conversions)
Wright_2019_raw <- dataset_process("data/Wright_2019/data.csv", Wright_2019_config, schema, resource_metadata)
Wright_2019 <- build_update_taxonomy(Wright_2019_raw, taxon_list)


austraits_raw <- build_combine(
        Falster_2005_1,
        Wright_2019,
        NULL)

# Combine all the studies into one resource
austraits <- build_add_version(austraits_raw, version_number, git_SHA)

# Save to file
dir.create("export/data/curr", FALSE, TRUE)
saveRDS(austraits, "export/data/curr/austraits.rds")
```

# remake

you can get the regular remake build pipeline using

```
 build_setup_pipeline(method="remake", dataset_ids = c("Falster_2005_1", "Wright_2019"))
 ```
 
 Note in both of the above you can also specify which datasetids to use, to only use a subset. The default is use everything. (Actually, that feature was always there). 
 
 # Others
 
 I'll also add options to enable parallel processing via
 
 - furrr: offers an option like purr:map
 - targets: pararllel but also with caching (like remake)

**Comment by yangsophieee** [comment]
I like it! Looks clean.

**Comment by ehwenk** [comment]
@dfalster Is this issue complete or were there additional pipelines to add?

**Comment by dfalster** [comment]
I am still working to get `targets` working, as a full time replacement for remake
