### ISSUE TITLE
Missing db_traits_pivot_wider function

### ISSUE THREAD

**Issue by hrlai** [traitecoevo/traits.build#183]
One of the recurring fail checks seems to come from a missing function? Has it been replaced by `dataset_check_not_pivoting`?

```
Error in `db_traits_pivot_wider(dataset$traits)`: could not find function "db_traits_pivot_wider"
Backtrace:
    ▆
 1. └─traits.build:::test_expect_no_warning(...)
 2.   └─base::tryCatch(...)
 3.     └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 4.       └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5.         └─base (local) doTryCatch(return(expr), name, parentenv, handler)
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 117 ]
```

**Comment by ehwenk** [comment]
Thank you for catching this. I thought I'd updated them all, but must have missed this one. It has been fixed with https://github.com/traitecoevo/traits.build/commit/8def1ca8e26bd95abe6ebb832378221291760881

**Comment by hrlai** [comment]
Cool, I can confirm that the error no longer appears. Thanks!

**Comment by ehwenk** [comment]
solved with https://github.com/traitecoevo/traits.build/commit/0f0517dba4305bf1a582cc2e5f010d3189721de7
