### ISSUE TITLE
Columns in `taxonomic_updates` table are all NA except `dataset_id`, `original_name` and `cleaned_name`

### ISSUE THREAD

**Issue by yangsophieee** [traitecoevo/traits.build#36]
Columns in `taxonomic_updates` table are all NA except `dataset_id`, `original_name` and `cleaned_name`. Previously most of them were NA but now they are all NA.

Columns in `taxa` table are also mostly NA.

**Comment by yangsophieee** [comment]
I figured out why -- it's because `taxon_list.csv` is empty so `build_update_taxonomy` won't do anything. What's the best way for me to regenerate `taxon_list.csv` for only the taxa in my test datasets?

**Comment by ehwenk** [comment]
@yangsophieee Can you see if this is still happening for you? Since the taxon_list.csv for tests has very few names, there will mostly be NA's - but info for the few taxa with details in taxon_list.csv should be filled in.

**Comment by yangsophieee** [comment]
@ehwenk mentioned you can use the code on the branch `update_taxon_list` on AusTraits with argument `overwrite = TRUE` to regenerate the `taxon_list.csv` for test datasets.

**Comment by yangsophieee** [comment]
We are now regenerating the `taxon_list.csv` with Lizzy's `build_update_taxon_list` function from AusTraits. First you move the test datasets to the `tests/testthat/data` folder, then run `build.R`, then source `build_update_taxon_list.R` in `tests/testthat/R`, then run the function on the built test database.
