### ISSUE TITLE
Create more explicit error message for "blank" datasets

### ISSUE THREAD

**Issue by yangsophieee** [traitecoevo/traits.build#4]
Referencing [this issue from austraits.build](https://github.com/traitecoevo/austraits.build/issues/732) opened by @ehwenk:

When there is a dataset that contains no information, usually due to a mistake in trait names being mapped in, you get this error:

```
Error in `dplyr::bind_rows()` at austraits.build/R/process.R:1391:4:
! Can't combine `..1$taxon_name` <character> and `..332$taxon_name` <logical>.
```
The empty dataset can be identified by `dir("data")[332]`

It would be good if you got an error message that had this error pattern, the error explicitly identified the problem for traits.build users outside of the AusTraits team.

**Comment by yangsophieee** [comment]
@ehwenk Would it be better to make this a `dataset_test` test? It's the easiest way I can think of to implement it. `dataset_test` already builds the dataset so all I would have to add is an error if the traits table is empty.

**Comment by ehwenk** [comment]
Yes, this is a good idea!
