### ISSUE TITLE
Test functions requiring user input

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/traits.build#41]
We currently don't tests any of the functions requiring interactive user input. This let some errors slip in (see #39 ). We should be able to adjust the interface slightly to enable testing. For example, see these posts

- https://stackoverflow.com/questions/65740390/how-to-test-a-function-that-depends-on-a-menu-user-input
- https://debruine.github.io/post/interactive-test/
- https://stackoverflow.com/questions/41372146/test-interaction-with-users-in-r-package

Ideally, these three functions would get tests added at some point

- metadata_add_locations
- metadata_add_contexts
- metadata_create_template

**Comment by yangsophieee** [comment]
`metadata_add_traits` also needs tests I think.
