### ISSUE TITLE
[traits.build testing] Testing for `dataset_test`

### ISSUE THREAD

**Issue by yangsophieee** [traitecoevo/traits.build#47]
Currently there isn't testing for `dataset_test` except a few basic lines checking that it works with argument `reporter = testthat::SilentReporter`. It would be nice if it could test that certain messages exist in the output when there are issues in the metadata.

**Comment by ehwenk** [comment]
solved with solved with https://github.com/traitecoevo/traits.build/commit/0f0517dba4305bf1a582cc2e5f010d3189721de7
