### ISSUE TITLE
How do you suppress default failure messages from `expect_` functions?

### ISSUE THREAD

**Issue by yangsophieee** [traitecoevo/traits.build#48]
To make `dataset_test` more accessible, I want to suppress default failure messages from `expect_` functions and only show the message that we have manually designed to the user.

![image](https://github.com/traitecoevo/traits.build/assets/78716301/7bb09392-b4a6-423e-95c6-535868951a8d)

E.g. We don't want the code and the `actual` and `expected` lines  to show. I tried looking into the customisation of error messages within the `expect_` documentation but couldn't figure it out. 
For example, in `expect_equal`:
- `object` and `expected`: "Both arguments supports limited unquoting to make it easier to generate readable failures within a function or for loop. See [quasi_label](vscode-webview://0himrfqpbn9qvtmpkamgvvl4gnieo9dm953pmjqq9uiegpb1tpu4/testthat/help/quasi_label) for more details."
-  `label`: "Used to customise failure messages. For expert use only." 

I tried customising these but it doesn't come out the way I want. In addition, the `info` argument is what we've been using and it's been soft-deprecated. I can't figure out why.

**Comment by dfalster** [comment]
Good idea.

I leveraged the testthat infrastructure in this function, but that's an unusual fit and I'm not sure it's the best fit.


I just came across this alternative, the 'validate' package. You set up rules, similar to tests, but more suited to data and the output format is different, perhaps more suitable?

https://data-cleaning.github.io/validate/

**Comment by dfalster** [comment]
Another option is 'assertr'

https://github.com/ropensci/assertr

**Comment by ehwenk** [comment]
See also issue #4 for a specific example of a cryptic message that we've worked out the meaning of, but which is a strong candidate for a custom error message.

**Comment by yangsophieee** [comment]
Another problem with the current `dataset_test` is that it prints out failure messages while the tests are running, and then it prints them out a second time with the 'results' of `dataset_test`. We only want one set of failure messages, otherwise it's very cluttered.
