### ISSUE TITLE
Vignettes are not building because missing `figures/` folder

### ISSUE THREAD

**Issue by yangsophieee** [traitecoevo/traits.build#52]
When running `devtools::check()`, an error occurs when building vignettes. I think it's because the figures folder is missing. In austraits.build it is located in docs/. The documentation files that are not building are: 'adding_data.Rmd' and 'traits.build.Rmd'. 

![image](https://github.com/traitecoevo/traits.build/assets/78716301/8092d125-197e-45f0-b2e0-5e45ffe6c163)

E.g. from 'traits.build.Rmd' it's looking for 'figures/logo.png':
![image](https://github.com/traitecoevo/traits.build/assets/78716301/ecca2de4-8fde-41d3-a0e1-79f66c4941f3)

**Comment by dfalster** [comment]
I fixed the issue with figures on develop (forgot to make a branch, whoops)

I'm not experiencing the same issues as you Sophie. I can run `devtools::check()` fine, and both vignettes build. 

Not sure what to suggest. Perhaps install the package first? You might have a really old version installed ?

**Comment by yangsophieee** [comment]
I tried it on my PC at home and it works now, thanks!
