### ISSUE TITLE
Explore `value_type` errors

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/traits.build#57]
There are 2 seemingly unrelated errors all related to `value_type` that probably have a common source:
- dataset_tests throws an odd  `value_type` error for all datasets
- the `methods` table currently has `value_type.x` and `value_type.y`, indicating it has been added to this table twice 

For a while I was wondering if the methods table shouldn't have value_type at all - but thinking that for now I'll leave it in the table once - and therefore also in schema

**Comment by yangsophieee** [comment]
The order of `value_type` and other columns in the methods table seems to change when I run `test_build_dataset` on different test datasets. Not sure if this is a real issue though but we might want a fixed order to the methods table columns.

**Comment by ehwenk** [comment]
closed with [8714247](https://github.com/traitecoevo/traits.build/commit/8714247b22744216c23d2c533f277b576b5d5d5f)
