### ISSUE TITLE
Read in `entity_type`, `value_type`, etc. from columns for long data formats

### ISSUE THREAD

**Issue by yangsophieee** [traitecoevo/traits.build#6]
Referencing [issue from austraits.build](https://github.com/traitecoevo/austraits.build/issues/725):

@ehwenk pointed out that when in long format, we might want to read in columns of data for things like `entity_type` and `value_type,` and that currently this isn't possible. The issue was fixed for wide format.

**Comment by ehwenk** [comment]
You can currently read in all ‘value_type’s from a single volume specified in through dataset$value_type but you can’t have partially fixed values and partially values read in from a column specified under a trait

**Comment by yangsophieee** [comment]
See issue from AusInverTraits as an [example](https://github.com/traitecoevo/ausinvertraits.build/issues/70). A good test dataset (from AusInverTraits) is `Couchman_1962`.

**Comment by yangsophieee** [comment]
Has been implemented on `read_metadata_fields_from_column_at_trait_level`, just need tests to be added.

**Comment by ehwenk** [comment]
closed with [8714247](https://github.com/traitecoevo/traits.build/commit/8714247b22744216c23d2c533f277b576b5d5d5f)

**Comment by yangsophieee** [comment]
Solved with this [commit](https://github.com/traitecoevo/traits.build/commit/3996a4df6a030bc4f2744db2267c0fc28e2fe14b).
