### ISSUE TITLE
Genus-level observations not appearing in the `traits` table

### ISSUE THREAD

**Issue by yangsophieee** [traitecoevo/traits.build#62]
Genus-level observations in `data.csv` are not appearing in the `traits` table for Test_2023_4. These are the 9 taxa that aren't making it to the `traits` table. They don't appear in `excluded_data` either so initially I was confused why I was losing 9 rows from the data.

![image](https://github.com/traitecoevo/traits.build/assets/78716301/0cac0708-c125-4561-b81b-cbff0234a341)

For AusTraits, it would work to align these using `taxon_list.csv`, e.g. "Diodia" -> "Diodia sp.", but could we add an AusTraits-specific error that detects genus-level observations (e.g. "Diodia") and adds them to the `excluded_data` table, instead of the data being completely lost? 

For other databases, we want `traits.build` to be applicable to different taxonomy criteria, so genus-level and above observations should be accepted (e.g. for AusInverTraits). Right now this isn't the case as the 9 rows of genus names are being lost.

**Comment by ehwenk** [comment]
It is actually that these taxa are being explicitly excluded in the `custom_R_code` for this study with the line

```
filter(str_detect(taxon_name, " "))
```
If that line is removed the taxa are in `austraits$traits`. And are included in `austraits$taxa` with `taxon_rank = Genus`

I think this is the functionality we want. If you agree @yangsophieee , let's close this issue.

**Comment by yangsophieee** [comment]
@ehwenk Whoops I clearly didn't pick up on that! Thanks for finding that out for me. Closing issue!
