### ISSUE TITLE
Allow units to be read in from a column

### ISSUE THREAD

**Issue by yangsophieee** [traitecoevo/traits.build#7]
Referencing [this issue from austraits.build](https://github.com/traitecoevo/austraits.build/issues/674) (which also affects AusInverTraits):

In `process.R`, many metadata fields can be read in through a column, such as `entity_type` and `value_type`. We have not ever added units to this list (see Lines 934-943 of `process.R`). The AusInverTraits project has instances where the same trait is documented in different units within a study. Currently they are having to use `custom_R_code` to align units for a given trait. It would make more sense to be able to specify a column under `metadata$traits$unit_in`.

This is particularly important since if you have long-format data and the value column is a mix of numeric and categorical data, you have to spit the data frame into numeric vs categorical portions before doing any manipulations to the values. See ABRS_1981 for an example.

**Comment by ehwenk** [comment]
This is an important functionality to add, but is going to require more changes to the code structure than any of the other "read from column" variables, as unit conversions occur already on row ~37 of process.R, at a time when you've just read in trait_name and unit_in from metadata[["traits"]], so each trait has a single unit_in attached to it. @dfalster I'm adding this to you list.

Solving issue #10 can hopefully occur as part of the same changes - problems with units in bins causes constant warnings. (We're considering values that come in from `bins` to be a weird category that don't get picked up by any excluded data tests, but it is probably time to properly integrate them.)

**Comment by ehwenk** [comment]
closed with [1636c31](https://github.com/traitecoevo/traits.build/commit/1636c3154d6ce1853ffd0b601f1eeab516826380)
