### ISSUE TITLE
location_id should be NA's for all `entity_type: species`

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/traits.build#72]
As I'm writing up tutorials for traits.build, I've discovered that there are observations for which  `entity_type: species` that have a `location_id`. 

They, correctly, do not have a `population_id`, but somehow are still assigned a `location_id`, presumably because they are read in from a row for which there is location information (for population-level or individual-level measurements).

We should:
1.  Actively set `location_id` to NA if `entity_type: species` - after all identifiers are created.
2. Add a test to confirm that, within a dataset, `location_id` always is NA for species-level measurements.

**Comment by yangsophieee** [comment]
I've fixed this [here](https://github.com/traitecoevo/traits.build/blob/7c9db8af6e41f0f39b570a25082f7d91e57caad0/R/process.R#L127). It now means that species-level measurements will have their `location_id` removed and hence any location-level metadata will not be assigned to them. Just checking that this is the intended workflow? @ehwenk

**Comment by ehwenk** [comment]
Yes, that is the intended workflow - if there is location-specific information, then it isn't actually a species-level observation, but instead a population-level observation, because the trait measurement(s) only refers to individuals in that location (a population), not to all individuals of the species. Changing this might uncover some errors - where we've declared `entity_type = species` when it should be `entity_type = population`. So we need to check that all studies still pivot.

**Comment by yangsophieee** [comment]
@ehwenk But previously if we declared `entity_type = species` there would be no `population_id` (as you said in your originally comment) even if there is a `location_id`, so it wouldn't affect whether studies still pivot, would it?

**Comment by ehwenk** [comment]
@yangsophieee Yes you're right - I don't think I was clear. If a value is declared to have `entity_type = species` but should be `entity_type = population` (i.e. there are two values for the same trait x species), then the pivot-test will fail and it will be obvious that entity_type should be population.
