### ISSUE TITLE
Add dataset test to confirm all metadata context property values are in data.csv

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/traits.build#75]
There is no longer (& maybe never was) a test in dataset tests to confirm that, for a given context property, all values listed in metadata are in the appropriate data.csv column. I thought such a test once existed, but looking back in history I can't find it.

Low priority right now, compared with getting the workflow stable and those tests written

**Comment by yangsophieee** [comment]
Maybe duplicate of #63

**Comment by ehwenk** [comment]
duplicate of issue #63
