### ISSUE TITLE
Need to use `life_stage` when creating `observation_id`'s

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/traits.build#9]
`sample_age_class` needs to be included in the list of columns that is used to generate unique `observation_id`'s . All other columns of information might be identical, but a measurement is made on plants of two different age classes and these need to be assigned unique observation_id's. This is not currently the case.

**Comment by dfalster** [comment]
Moved to https://github.com/traitecoevo/traits.build/issues/14

**Comment by yangsophieee** [comment]
This should be `life_stage` not `sample_age_class` right? Was that the old name? @ehwenk

**Comment by ehwenk** [comment]
> This should be `life_stage` not `sample_age_class` right? Was that the old name? @ehwenk

yes

**Comment by ehwenk** [comment]
Edit made

**Comment by ehwenk** [comment]
closed with [8714247](https://github.com/traitecoevo/traits.build/commit/8714247b22744216c23d2c533f277b576b5d5d5f)
