### ISSUE TITLE
Make `austraits` package functions part of workflow or testing

### ISSUE THREAD

**Issue by yangsophieee** [traitecoevo/traits.build#93]
Brought to my attention by @ehwenk:

Currently there is no testing to check that the `austraits` functions `join_...`, `as_wide_table`, etc. work on the austraits output. This would be useful, as there have been previous releases where there have been issues in the data preventing `as_wide_table` from working.

@ehwenk Thinking about it a bit more, I'm a bit confused how this would work. Is the aim of this to make sure the `austraits` functions work as intended, or whether the data doesn't have issues in it, assuming that the `austraits` functions work as intended?

If this is added as a test within `traits.build`, it would only test whether the `austraits` functions work on the test datasets. In order to test if a final database output doesn't have any issues in it, couldn't we just run `dataset_test()` on the whole database and check no failures + everything pivots wider?

**Comment by ehwenk** [comment]
The assumption is that unless the workflow changes, it is an error within a dataset. It is therefore a test that should either be part of testdata.R or a test that runs on a fully built database?

I see this as an extension of the errors that are now being quickly picked up by the pivot test, that previously only appeared when we sporadically tried to use austraits pivot functions. It would be more efficient than suddenly discovering, as I did today, that a function like `join_contexts` is no longer working.

**Comment by yangsophieee** [comment]
Yeah I think testdata.R would work well. 

I'm not too sure of a place where a test would run on a fully built database. Maybe [here](https://github.com/traitecoevo/austraits.build/blob/develop/.github/workflows/check-build.yml), after AusTraits is built.

**Comment by yangsophieee** [comment]
Already messaged @ehwenk about this but putting this here so we don't forget: 

Should we really make it so that `dataset_test` has failures for `excluded_data` rows? Like what if those rows should legitimately be `excluded_data` because they are out of range, or don't fit the categorical values in our trait dictionary? Do you think the user should instead manually exclude them in the `exclude_observations` metadata section? I can imagine that could get tedious.

**Comment by yangsophieee** [comment]
I've added the tests but it seems they are failing because `austraits` functions are not fully functional yet. I've tried using the `changes-for-v5-austraits.build` branch but there's still `treatment_id` instead of `treatment_context_id` in the branch. 

So leaving this branch on hold for now.
