### ISSUE TITLE
`exclude_observations` field not working

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/traits.build#96]
The metadata[["exclude_observations"]] field is currently not causing data to be moved to the `excluded_data` table. This is something that has been broken recently (in the past 1-2 weeks). 

I initially was looking at the austraits.build study `Fonseca_2000` and wondered if it was because the names listed are actually `originial_names` (they are all capitalised as part of automatic processing), but then built all of AusTraits and can confirm there are no values appearing in austraits$excluded_data with the error "Observation excluded in metadata" .

```
> austraits$excluded_data %>% filter(error == "Observation excluded in metadata")
# A tibble: 0 × 27
```

**Comment by ehwenk** [comment]
It looks like the change occurred with commit https://github.com/traitecoevo/traits.build/commit/119502867a6ce5b3d914cd9c78101f7e9843af33

Previous code, Line 659 Process.R:
```
dplyr::mutate(error = ifelse(data[[v]] %in% fix[[v]]$find, "Observation excluded in metadata", .data$error))
```

Current code, Line 881 Process.R:
```
      dplyr::mutate(
        error = ifelse(.data$trait_name == v & .data$value %in% fix[[v]]$find,
        "Observation excluded in metadata", .data$error))
```

**Comment by dfalster** [comment]
How could I easily trigger this?

**Comment by dfalster** [comment]
never mind, I see, `Fonseca_2000`

**Comment by yangsophieee** [comment]
Closed with this commit: https://github.com/traitecoevo/traits.build/commit/dda867348f2a9d391f4ae52d4515f0c86be3567f
